version: "3.9"
services:
  pipedrive-task-service:
    build:
      context: ./
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      HTTP_PORT: 3000
      MYSQL_DB: organisation
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - pipedrive

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    networks:
      pipedrive:
        aliases:
          - mysql.pipedrive
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organisation

networks:
  pipedrive:
    driver: bridge
